repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.4"
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
