[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.0.265",
    "black>=23.3.0",
    "pre-commit>=3.3.1",
    "pytest>=7.3.1",
    "httpx>=0.24.1",
]
[project]
name = "api"
description = "Ludotheque"
authors = [
    {name = "Benoît", email = "benoit.dien@gmail.com"},
]
dependencies = [
    "peewee>=3.16.2",
    "requests>=2.30.0",
    "fastapi>=0.95.1",
    "uvicorn[standard]>=0.22.0",
    "python-multipart>=0.0.6",
]
requires-python = ">=3.11"
license = {text = "GPL2"}
dynamic = [ "version" ]

[tool.pdm.version]
source = "scm"

[tool.ruff]
select = ["E", "F", "B", "RUF", "UP", "SIM", "S"]
ignore = ["E402", "E501"]
# E402: module level import not at top of file
# E501: Line too loog

target-version = "py311"

[tool.ruff.mccabe]
max-complexity = 28

[tool.ruff.per-file-ignores]
"src/tests_api/*.py" = ["S101"]
# S101: Use of assert

[tool.pdm.scripts]
api = {shell = "cd src/api && uvicorn main:app --reload"}
webui = {shell = "cd src/webui && pnpm run dev --host 0.0.0.0"}

[tool.pytest.ini_options]
addopts = "--ignore=__pypackages__"
